name: CD

on:
  push:
    branches:
      - 'main'

  schedule:
    - cron: '0 * * * *' # run every hour
  workflow_dispatch:
    

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_PAGES_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK }}

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        env: # Or as an environment variable
         NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          npm install
          npm start
          hugo

      # - name: Commit updated content
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Sync content with Notion

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
